### ISSUE TITLE
지금까지 미구현 사항 및 이슈

### ISSUE THREAD

**Issue by skojphy** [kheeyaa/Who-ate-my-fish#50]
- [x] 시민 n명/ 마피아 n명 (석규님 코드 확인 필요)

- [x] 게임종료시 상태값 초기화

- [x] 투표 종료 후 빨간 테두리 제거

- [x] 밤 투표 이후 감옥 고양이 표시 => 밤 투표 이후 감옥 간 고양이 정보 서버단에서 뿌리는지 확인 필요

- [x] 비활성화 시 채팅 영역 및 투표 영역 반투명 처리

- [x] 죽은고양이 투표 못하게처리

@kheeyaa @dbstjrrb12 @hustle-dev

**Comment by kheeyaa** [comment]
@dbstjrrb12 @hustle-dev

**Comment by hustle-dev** [comment]
밤 투표 이후 감옥 고양이 표시 완료

**Comment by hustle-dev** [comment]
1시 49분 시민 n명/ 마피아 n명 코드 정상작동확인

**Comment by hustle-dev** [comment]
초기화는 다 해두엇는데 한가지 문제점이 다시 하기 버튼을 눌러서 진입할때의 문제가 있음

--> 알아봐야 할듯

**Comment by hustle-dev** [comment]
남은 할일
- [ ] 게임종료시 상태값 초기화
- [ ] 비활성화 시 채팅 영역 및 투표 영역 반투명 처리
- [ ]죽은고양이 투표 못하게처리
- [ ] ~ (은) 마피아 였습니다

**Comment by kheeyaa** [comment]
- [ ] 투표시 이미지 이외의 영역을 클릭했을 경우 빨간 동그라미가 되는 것을 막아야함
